type User @table {
  firebaseUid: String! @default(expr: "auth.uid")
  displayName: String!
  createdAt: Timestamp!
  email: String
  eventLimit: Int
}

type Event @table {
  name: String!
  eventDate: Date!
  createdAt: Timestamp!
  photoLimit: Int
  owner: User!
  joinCode: String!
}

type Photo @table {
  imageUrl: String!
  createdAt: Timestamp!
  event: Event!
  uploader: User!
}

type Analytic @table {
  eventType: String!
  timestamp: Timestamp!
  userIdentifier: String
  event: Event!
}

type EventMember @table(key: ["event", "user"]) {
  event: Event!
  user: User!
  joinedAt: Timestamp!
}
