query AllEvents
@auth(
  level: USER
  insecureReason: "This operation is safe to expose to all logged in users."
) {
  events {
    id
    name
    eventDate
    photoLimit
    createdAt
    owner {
      id
      displayName
    }
  }
}

query MyPhotos @auth(level: USER) {
  photos(where: { uploader: { firebaseUid: { eq_expr: "auth.uid" } } }) {
    id
    imageUrl
    createdAt
    event {
      id
      name
    }
  }
}

query EventPhotos($eventId: UUID!) @auth(level: USER) {
  photos(where: { event: { id: { eq: $eventId } } }) {
    id
    imageUrl
    createdAt
    event {
      id
      name
    }
  }
}

query MyEvents @auth(level: USER) {
  events(where: { owner: { firebaseUid: { eq_expr: "auth.uid" } } }) {
    id
    name
    eventDate
    joinCode
    createdAt
  }
}

mutation CreateEvent(
  $name: String!
  $eventDate: Date!
  $photoLimit: Int
  $ownerId: UUID!
  $joinCode: String!
) @auth(level: USER) {
  event_insert(
    data: {
      name: $name
      eventDate: $eventDate
      photoLimit: $photoLimit
      owner: { id: $ownerId }
      createdAt_expr: "request.time"
      joinCode: $joinCode
    }
  )
}

mutation UploadPhoto($eventId: UUID!, $imageUrl: String!, $uploaderId: UUID!)
@auth(level: USER) {
  photo_insert(
    data: {
      eventId: $eventId
      imageUrl: $imageUrl
      uploader: { id: $uploaderId }
      createdAt_expr: "request.time"
    }
  )
}

mutation CreateUser(
  $displayName: String!
  $email: String!
  $firebaseUid: String!
) @auth(level: USER) {
  user_insert(
    data: {
      displayName: $displayName
      email: $email
      firebaseUid: $firebaseUid
      createdAt_expr: "request.time"
    }
  )
}

mutation DeleteEvent($id: UUID!) @auth(level: USER) {
  event_delete(id: $id)
}

mutation DeleteUser($id: UUID!) @auth(level: USER) {
  user_delete(id: $id)
}

mutation DeletePhoto($id: UUID!) @auth(level: USER) {
  photo_delete(id: $id)
}

mutation JoinEvent($eventId: UUID!, $userId: UUID!) @auth(level: USER) {
  eventMember_insert(
    data: {
      eventId: $eventId
      user: { id: $userId }
      joinedAt_expr: "request.time"
    }
  )
}

query GetEventByCode($joinCode: String!) @auth(level: USER) {
  events(where: { joinCode: { eq: $joinCode } }) {
    id
    name
    eventDate
    joinCode
    owner {
      displayName
    }
  }
}

query MyJoinedEvents @auth(level: USER) {
  eventMembers(where: { user: { firebaseUid: { eq_expr: "auth.uid" } } }) {
    event {
      id
      name
      eventDate
      owner {
        displayName
      }
    }
  }
}

query GetCurrentUser($firebaseUid: String!) @auth(level: USER) {
  users(where: { firebaseUid: { eq: $firebaseUid } }) {
    id
    displayName
    firebaseUid
  }
}

query GetEvent($id: UUID!) @auth(level: USER) {
  events(where: { id: { eq: $id } }) {
    id
    name
    eventDate
    joinCode
    photoLimit
    owner {
      displayName
    }
  }
}
