query AllEvents
@auth(
  level: USER
  insecureReason: "This operation is safe to expose to all logged in users."
) {
  events {
    id
    name
    eventDate
    photoLimit
    createdAt
    owner {
      id
      displayName
    }
  }
}

query MyPhotos @auth(level: USER) {
  photos(where: { uploaderId: { eq_expr: "auth.uid" } }) {
    id
    imageUrl
    createdAt
    event {
      id
      name
    }
  }
}

query MyEvents @auth(level: USER) {
  events(where: { ownerId: { eq_expr: "auth.uid" } }) {
    id
    name
    eventDate
    photoLimit
    createdAt
  }
}

mutation CreateEvent($name: String!, $eventDate: Date!, $photoLimit: Int)
@auth(level: USER) {
  event_insert(
    data: {
      name: $name
      eventDate: $eventDate
      photoLimit: $photoLimit
      ownerId_expr: "auth.uid"
      createdAt_expr: "request.time"
    }
  )
}

mutation UploadPhoto($eventId: UUID!, $imageUrl: String!) @auth(level: USER) {
  photo_insert(
    data: {
      eventId: $eventId
      imageUrl: $imageUrl
      uploaderId_expr: "auth.uid"
      createdAt_expr: "request.time"
    }
  )
}

mutation CreateUser($displayName: String!, $email: String!, $photoUrl: String!)
@auth(level: USER) {
  user_insert(
    data: {
      displayName: $displayName
      email: $email
      photoUrl: $photoUrl
      createdAt_expr: "request.time"
    }
  )
}
